### ISSUE TITLE
Running 'next' returns previous track

### ISSUE THREAD

**Issue by developius** [dronir/SpotifyControl#17]
When running
```SpotifyControl next```
the previous track is returned, not the one _now_ playing.

**Comment by byteminer** [comment]
Adding a small delay to the beginning of the "Now Playing" section of the script fixes this, as the player doesn't switch instantly.
Something like ```delay 0.1``` should suffice.

**Comment by developius** [comment]
@byteminer, on line 170 https://github.com/dronir/SpotifyControl/blob/master/SpotifyControl#L170?

**Comment by byteminer** [comment]
That's the block. Put the delay in front of this line: https://github.com/dronir/SpotifyControl/blob/master/SpotifyControl#L167

**Comment by developius** [comment]
Thanks

**Comment by developius** [comment]
I'll open a PR tomorrow for this fix if you want?

**Comment by byteminer** [comment]
Fine with me.

**Comment by digitaljhelms** [comment]
:+1:
