### ISSUE TITLE
Play playlist / album / track + search?

### ISSUE THREAD

**Issue by stevelacey** [dronir/SpotifyControl#2]
This really nicely wraps up a load of ropey AppleScripts I had written myself, the cherry on top would be a command which you can pass a Spotify URI too to start playing a playlist / album / track.

Beyond that, basic search would also be amazing for those using Spotify over SSH.

**Comment by hnarayanan** [comment]
(I stumbled upon this project when I was Googling for an breaking changes introduced to the AppleScript interface with Spotify 1.0+)

I just stopped by to say that I have a [similar project](https://github.com/hnarayanan/shpotify) that includes this feature for searching and playing a playlist/track/artist etc.

**Comment by mahi97** [comment]
I had written a shell command to connect to Spotify search API and grep URI of artist, album or track and pass it to Spotify play URI.
so now you can use Spotify play artist/album/track [name] to search  Spotify and play your wanted song. 
#23
