### ISSUE TITLE
Repeat & Shuffle toggle specific values

### ISSUE THREAD

**Issue by NoX1De** [dronir/SpotifyControl#28]
Would it be possible to modify the shuffle & repeat toggle so that we can specify for example:

spotify shuffle on
spotify shuffle off
spotify repeat on
spotify repeat off

It looks like the Spotify AppleScript API has the ability to check the current status of both shuffle & repeat so building in a check to see if say we issued the command:

spotify shuffle on

However, if shuffle was already on it would just then spit out "Shuffle is already toggled on." and take no action...same for repeat...since Spotify likes to automatically disable repeat and shuffle on us it would be nice to use this new way to automate keeping shuffle and repeat enabled.  I realize we can do that now but it requires something like:

/usr/local/bin/spotify repeat && /usr/local/bin/spotify shuffle && /usr/local/bin/spotify repeat && /usr/local/bin/spotify shuffle

To be scheduled to run via cron...but say a reboot or Spotify update occurs and shuffle and repeat get set to disabled then this cron job would just enable and disable them again...in other words doing it this way with no method to specify on or off is crude and requires both shuffle and repeat to always be in the on state before it runs for this cronjob to function as keeping them enabled. 

Let me know if I'm missing something or if there is a better way to do this as it stands currently.

Thank you!

**Comment by dronir** [comment]
This sounds like a good idea. I'll look into it.

**Comment by dronir** [comment]
Added this functionality. Now `spotify shuffle [on|off]` will set it accordingly, and without the parameter it gets toggled.

**Comment by NoX1De** [comment]
You're the man! Thank you much sir for such a quick turn around on this.
