### ISSUE TITLE
Is it possible to "play playlist"?

### ISSUE THREAD

**Issue by jasonnmark** [dronir/SpotifyControl#30]
I'm guessing it's not permitted by Spotify since AppleScript also doesn't seem to permit it but figured I'd ask in case I missed something.

**Comment by dronir** [comment]
I'm not sure how it would exactly work, but it's possible to play a song _in a context_, i.e. probably say something like "play this song (as a part of this playlist)", which (I assume) would play that song and then continue with that playlist from that song onwards, but I'm not sure how to exactly implement that.

I'm not really devoting a lot of brainpower to this project anymore, but if anyone wants to look into it, I'd be happy with a reasonable pull request.

Here's the relevant AppleScript hook:

```
<command name="play track" code="spfyPCtx" description="Start playback of a track in the given context.">
  <access-group identifier="com.spotify.playback"/>
  <cocoa class="SPPlayTrackScriptCommand"/>
  <direct-parameter description="the URI of the track to play" type="text"/>
  <parameter name="in context" code="cotx" description="the URI of the context to play in" type="text" optional="yes">
    <cocoa key="context"/>
  </parameter>
</command>
```

**Comment by jasonnmark** [comment]
Very cool... unfortunately the playlist I want to play with a script is "Discover Weekly" and Spotify changes the songs in that list ever week... doh.

**Comment by jackweath** [comment]
Well if you know which playlist and can get the URI (by right clicking, and choosing share in the client), then you can just play the playlist from the URI. So for my Discover Weekly (and playing in shuffle) I could run:
```
SpotifyControl play spotify:user:spotify:playlist:37i9dQZEVXcW3gnIv4avn0
```

The URI is obviously universal so you only need to get it once after the playlist is made; i.e. it doesn't change when Spotify change the tracks in your Discover Weekly playlist.
