### ISSUE TITLE
Spotify AppleScript not working in version 1.0.1

### ISSUE THREAD

**Issue by soberstadt** [dronir/SpotifyControl#9]
I'm getting `Expected end of line but found identifier.` errors on all spotify applescript commands. Are you experiencing the same thing?

**Comment by soberstadt** [comment]
So I found this for anyone else who might get this error: https://twitter.com/SpotifyPlatform/status/575615437813202944

**Comment by lmanuelcb** [comment]
Yes, I hope they fix this soon.. I'm working on a project..

**Comment by phcyso** [comment]
This is fixed now in spotify 1.0.3.101

**Comment by soberstadt** [comment]
:+1:
